name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        
    - name: Touch local properties
      run: touch local.properties

    - name: Add Api Key
      run: echo "apiKey=\"\"" >> local.properties
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Node Database Test
      run: ./gradlew NodeDatabaseTest
      
    - name: Android Test Results
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}
